export const CHAT_CLIENT_PROTOCOL = "wc";
export const CHAT_CLIENT_VERSION = 1;
export const CHAT_CLIENT_CONTEXT = "chat";

export const CHAT_CLIENT_STORAGE_PREFIX = `${CHAT_CLIENT_PROTOCOL}@${CHAT_CLIENT_VERSION}:${CHAT_CLIENT_CONTEXT}:`;
